- name: Build APK with EAS (Cloud)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          npx expo prebuild --non-interactive
          npx eas build --platform android --profile preview --non-interactive
